/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ProductSummary;
import Repository.RepositoryProvider;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class RecordView extends javax.swing.JFrame {

    /**
     * Creates new form RecordView
     */
    private RepositoryProvider provider;
    public RecordView() {
        initComponents();
        
        provider = new RepositoryProvider();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logBackground = new javax.swing.JPanel();
        logoSide1 = new javax.swing.JPanel();
        logoSide = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        signOut = new javax.swing.JButton();
        addRecord = new javax.swing.JButton();
        viewRecord = new javax.swing.JButton();
        logoSide3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logoSide6 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        logoSide5 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        PP_TotalSoldLbl = new javax.swing.JLabel();
        PP_OverallSalesLbl = new javax.swing.JLabel();
        PP_OverallProfitLbl = new javax.swing.JLabel();
        PP_PHPLbl_OP = new javax.swing.JLabel();
        PPPtotalSold = new javax.swing.JLabel();
        PP_PHPLbl_OS = new javax.swing.JLabel();
        PPPoverallSales = new javax.swing.JLabel();
        PPPoverallProfit = new javax.swing.JLabel();
        PPPview = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        CP_TotalSoldLbl = new javax.swing.JLabel();
        CP_OverallSalesLbl = new javax.swing.JLabel();
        CP_OverallProfitLbl = new javax.swing.JLabel();
        CP_PHPLbl_OP = new javax.swing.JLabel();
        CPPtotalSold = new javax.swing.JLabel();
        CP_PHPLbl_OverallSales = new javax.swing.JLabel();
        CPPoverallSales = new javax.swing.JLabel();
        CPPoverallProfit = new javax.swing.JLabel();
        CPPview = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logBackground.setBackground(new java.awt.Color(246, 246, 246));
        logBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoSide1.setBackground(new java.awt.Color(251, 215, 9));
        logoSide1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoSide.setBackground(new java.awt.Color(251, 215, 9));
        logoSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/logo_dashboard.png"))); // NOI18N
        logoSide.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        logoSide1.add(logoSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 80));

        signOut.setBackground(new java.awt.Color(251, 215, 9));
        signOut.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        signOut.setForeground(new java.awt.Color(38, 38, 38));
        signOut.setText("SIGN-OUT");
        signOut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        signOut.setFocusPainted(false);
        signOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signOutMouseExited(evt);
            }
        });
        signOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutActionPerformed(evt);
            }
        });
        logoSide1.add(signOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 140, 43));

        addRecord.setBackground(new java.awt.Color(251, 215, 9));
        addRecord.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        addRecord.setForeground(new java.awt.Color(38, 38, 38));
        addRecord.setText("ADD RECORD");
        addRecord.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addRecord.setFocusPainted(false);
        addRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addRecordMouseExited(evt);
            }
        });
        addRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecordActionPerformed(evt);
            }
        });
        logoSide1.add(addRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 140, 43));

        viewRecord.setBackground(new java.awt.Color(38, 38, 38));
        viewRecord.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        viewRecord.setForeground(new java.awt.Color(251, 215, 9));
        viewRecord.setText("VIEW RECORD");
        viewRecord.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        viewRecord.setFocusPainted(false);
        viewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRecordActionPerformed(evt);
            }
        });
        logoSide1.add(viewRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 140, 43));

        logBackground.add(logoSide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 140, 950));

        logoSide3.setBackground(new java.awt.Color(38, 38, 38));
        logoSide3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(142, 149, 153));
        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("You are currently viewing the records");
        logoSide3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 360, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/waveHand.png"))); // NOI18N
        logoSide3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Marie's Printing Services Sales Management System");
        logoSide3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 870, -1));

        logBackground.add(logoSide3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 1170, 100));

        jLabel1.setBackground(new java.awt.Color(142, 149, 153));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Summary");
        logBackground.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/user_profile.png"))); // NOI18N
        logBackground.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, 90, 90));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("PRODUCT RECORDS");
        logBackground.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 190, 40));

        logoSide6.setBackground(new java.awt.Color(38, 38, 38));
        logoSide6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel27.setBackground(new java.awt.Color(38, 38, 38));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        logoSide6.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 590, 10));

        jLabel43.setFont(new java.awt.Font("Trebuchet MS", 1, 32)); // NOI18N
        jLabel43.setForeground(java.awt.Color.white);
        jLabel43.setText("PRINTING PRODUCT DETAILS");
        logoSide6.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(251, 215, 9));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        logoSide6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1130, 10));

        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "PRODUCT NAME", "NO. OF SOLD", "SALES", "PROFIT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table1);

        jScrollPane4.setViewportView(jScrollPane2);

        logoSide6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1130, 160));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/printer.png"))); // NOI18N
        logoSide6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 70, 80));

        logBackground.add(logoSide6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, 1170, 370));

        logoSide5.setBackground(new java.awt.Color(38, 38, 38));
        logoSide5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(251, 215, 9));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(251, 215, 9));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel14MouseExited(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Trebuchet MS", 1, 32)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(38, 38, 38));
        jLabel30.setText("PHOTO PAPER PRINTING");
        jPanel14.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel31.setBackground(new java.awt.Color(142, 149, 153));
        jLabel31.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Hover for overall details");
        jPanel14.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/info.png"))); // NOI18N
        jPanel14.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, 40));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 110));

        jPanel15.setBackground(new java.awt.Color(38, 38, 38));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 420, 10));

        PP_TotalSoldLbl.setBackground(new java.awt.Color(142, 149, 153));
        PP_TotalSoldLbl.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        PP_TotalSoldLbl.setForeground(new java.awt.Color(38, 38, 38));
        PP_TotalSoldLbl.setText("Total Sold:");
        jPanel13.add(PP_TotalSoldLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 70, 40));

        PP_OverallSalesLbl.setBackground(new java.awt.Color(142, 149, 153));
        PP_OverallSalesLbl.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        PP_OverallSalesLbl.setForeground(new java.awt.Color(38, 38, 38));
        PP_OverallSalesLbl.setText("Overall Sales:");
        jPanel13.add(PP_OverallSalesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, 40));

        PP_OverallProfitLbl.setBackground(new java.awt.Color(142, 149, 153));
        PP_OverallProfitLbl.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        PP_OverallProfitLbl.setForeground(new java.awt.Color(38, 38, 38));
        PP_OverallProfitLbl.setText("Overall Profit:");
        jPanel13.add(PP_OverallProfitLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 40));

        PP_PHPLbl_OP.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        PP_PHPLbl_OP.setForeground(new java.awt.Color(38, 38, 38));
        PP_PHPLbl_OP.setText("PHP");
        jPanel13.add(PP_PHPLbl_OP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        PPPtotalSold.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        PPPtotalSold.setForeground(new java.awt.Color(38, 38, 38));
        PPPtotalSold.setText("0");
        jPanel13.add(PPPtotalSold, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 40, -1));

        PP_PHPLbl_OS.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        PP_PHPLbl_OS.setForeground(new java.awt.Color(38, 38, 38));
        PP_PHPLbl_OS.setText("PHP");
        jPanel13.add(PP_PHPLbl_OS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        PPPoverallSales.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        PPPoverallSales.setForeground(new java.awt.Color(38, 38, 38));
        PPPoverallSales.setText("0.00");
        jPanel13.add(PPPoverallSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        PPPoverallProfit.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        PPPoverallProfit.setForeground(new java.awt.Color(38, 38, 38));
        PPPoverallProfit.setText("0.00");
        jPanel13.add(PPPoverallProfit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        PPPview.setBackground(new java.awt.Color(38, 38, 38));
        PPPview.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        PPPview.setForeground(new java.awt.Color(255, 255, 255));
        PPPview.setText("SPECIFIC DETAILS");
        PPPview.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PPPview.setFocusPainted(false);
        PPPview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PPPviewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PPPviewMouseExited(evt);
            }
        });
        PPPview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPPviewActionPerformed(evt);
            }
        });
        jPanel13.add(PPPview, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 180, 70));

        logoSide5.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 460, 270));

        jPanel16.setBackground(new java.awt.Color(251, 215, 9));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(251, 215, 9));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel17MouseExited(evt);
            }
        });
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Trebuchet MS", 1, 32)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(38, 38, 38));
        jLabel36.setText("COSCARD/PHOTOCARD");
        jPanel17.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 420, -1));

        jLabel37.setBackground(new java.awt.Color(142, 149, 153));
        jLabel37.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setText("Hover for overall details");
        jPanel17.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/info.png"))); // NOI18N
        jPanel17.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 30, 40));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 110));

        jPanel18.setBackground(new java.awt.Color(38, 38, 38));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 420, 10));

        CP_TotalSoldLbl.setBackground(new java.awt.Color(142, 149, 153));
        CP_TotalSoldLbl.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        CP_TotalSoldLbl.setForeground(new java.awt.Color(38, 38, 38));
        CP_TotalSoldLbl.setText("Total Sold:");
        jPanel16.add(CP_TotalSoldLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 70, 40));

        CP_OverallSalesLbl.setBackground(new java.awt.Color(142, 149, 153));
        CP_OverallSalesLbl.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        CP_OverallSalesLbl.setForeground(new java.awt.Color(38, 38, 38));
        CP_OverallSalesLbl.setText("Overall Sales:");
        jPanel16.add(CP_OverallSalesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, 40));

        CP_OverallProfitLbl.setBackground(new java.awt.Color(142, 149, 153));
        CP_OverallProfitLbl.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        CP_OverallProfitLbl.setForeground(new java.awt.Color(38, 38, 38));
        CP_OverallProfitLbl.setText("Overall Profit:");
        jPanel16.add(CP_OverallProfitLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 40));

        CP_PHPLbl_OP.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        CP_PHPLbl_OP.setForeground(new java.awt.Color(38, 38, 38));
        CP_PHPLbl_OP.setText("PHP");
        jPanel16.add(CP_PHPLbl_OP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        CPPtotalSold.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        CPPtotalSold.setForeground(new java.awt.Color(38, 38, 38));
        CPPtotalSold.setText("0");
        jPanel16.add(CPPtotalSold, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 30, -1));

        CP_PHPLbl_OverallSales.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        CP_PHPLbl_OverallSales.setForeground(new java.awt.Color(38, 38, 38));
        CP_PHPLbl_OverallSales.setText("PHP");
        jPanel16.add(CP_PHPLbl_OverallSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        CPPoverallSales.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        CPPoverallSales.setForeground(new java.awt.Color(38, 38, 38));
        CPPoverallSales.setText("0.00");
        jPanel16.add(CPPoverallSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        CPPoverallProfit.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        CPPoverallProfit.setForeground(new java.awt.Color(38, 38, 38));
        CPPoverallProfit.setText("0.00");
        jPanel16.add(CPPoverallProfit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        CPPview.setBackground(new java.awt.Color(38, 38, 38));
        CPPview.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        CPPview.setForeground(new java.awt.Color(255, 255, 255));
        CPPview.setText("SPECIFIC DETAILS");
        CPPview.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CPPview.setFocusPainted(false);
        CPPview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CPPviewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CPPviewMouseExited(evt);
            }
        });
        CPPview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPPviewActionPerformed(evt);
            }
        });
        jPanel16.add(CPPview, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 180, 70));

        logoSide5.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 460, 270));

        logBackground.add(logoSide5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 1170, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMouseEntered
        signOut.setBackground(new Color(38,38,38,255));
        signOut.setForeground(new Color(251,215,9,255));
    }//GEN-LAST:event_signOutMouseEntered

    private void signOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMouseExited
        signOut.setBackground(new Color(251,215,9,255));
        signOut.setForeground(new Color(38,38,38,255));
    }//GEN-LAST:event_signOutMouseExited

    private void signOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutActionPerformed
        int result = JOptionPane.showConfirmDialog(logBackground,"Are you sure want to sign-out?","", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            this.dispose();
            new LoginView().setVisible(true);
        }
    }//GEN-LAST:event_signOutActionPerformed

    private void addRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRecordMouseEntered
        addRecord.setBackground(new Color(38,38,38,255));
        addRecord.setForeground(new Color(251,215,9,255));
    }//GEN-LAST:event_addRecordMouseEntered

    private void addRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRecordMouseExited
        addRecord.setBackground(new Color(251,215,9,255));
        addRecord.setForeground(new Color(38,38,38,255));
    }//GEN-LAST:event_addRecordMouseExited

    private void addRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecordActionPerformed
        this.dispose();
        new AddRecordView().setVisible(true);
    }//GEN-LAST:event_addRecordActionPerformed

    private void viewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewRecordActionPerformed

    private void jPanel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseEntered
        PP_OverallSalesLbl.setVisible(true);
        PP_OverallProfitLbl.setVisible(true);
        PP_TotalSoldLbl.setVisible(true);
        PP_PHPLbl_OS.setVisible(true);
        PP_PHPLbl_OP.setVisible(true);
        PPPoverallSales.setVisible(true);
        PPPoverallProfit.setVisible(true);
        PPPtotalSold.setVisible(true);
        PPPview.setVisible(false);

        // Request To DB
        ArrayList<ProductSummary> prod_sum_arr = provider.getProductRepo().getProductSummaries("Photopaper");
        
        // Aggregate to Single Value
        int TotalQty = 0;
        double TotalSales = 0;
        double TotalProfit = 0;
        
        for( ProductSummary prod_sum : prod_sum_arr ) {
            TotalQty += prod_sum.getQty();
            TotalSales += prod_sum.getSales();
            TotalProfit += prod_sum.getProfit();
        }
        
        // Show Totals
        PPPoverallSales.setText(Double.toString(TotalSales));
        PPPoverallProfit.setText(Double.toString(TotalProfit));
        PPPtotalSold.setText(Integer.toString(TotalQty));
    }//GEN-LAST:event_jPanel14MouseEntered

    private void jPanel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseExited
        PP_OverallSalesLbl.setVisible(false);
        PP_OverallProfitLbl.setVisible(false);
        PP_TotalSoldLbl.setVisible(false);
        PP_PHPLbl_OS.setVisible(false);
        PP_PHPLbl_OP.setVisible(false);
        PPPoverallSales.setVisible(false);
        PPPoverallProfit.setVisible(false);
        PPPtotalSold.setVisible(false);
        PPPview.setVisible(true);

    }//GEN-LAST:event_jPanel14MouseExited

    private void PPPviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PPPviewMouseEntered
        PPPview.setBackground(Color.WHITE);
        PPPview.setForeground(new Color(38,38,38,255));
    }//GEN-LAST:event_PPPviewMouseEntered

    private void PPPviewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PPPviewMouseExited
        PPPview.setBackground(new Color(38,38,38,255));
        PPPview.setForeground(Color.WHITE);
    }//GEN-LAST:event_PPPviewMouseExited

    private void PPPviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPPviewActionPerformed
        // TODO add your handling code here:
        jLabel43.setText("PHOTO PAPER PRINTING");

        // Request To DB
        ArrayList<ProductSummary> prod_sum_arr = provider.getProductRepo().getProductSummaries("Photopaper");
        
        // Aggregate to Single Value
        int TotalQty = 0;
        double TotalSales = 0;
        double TotalProfit = 0;
        
        DefaultTableModel tableModel = (DefaultTableModel)table1.getModel();
        tableModel.setRowCount(0);
        
        for( ProductSummary prod_sum : prod_sum_arr ) {
            tableModel.addRow(
                    new Object[]{
                        prod_sum.getProductId(),
                        prod_sum.getName(),
                        prod_sum.getQty(),
                        prod_sum.getSales(),
                        prod_sum.getProfit()
                    }
            );
        }
    }//GEN-LAST:event_PPPviewActionPerformed

    private void jPanel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseEntered
        CP_OverallSalesLbl.setVisible(true);
        CP_OverallProfitLbl.setVisible(true);
        CP_TotalSoldLbl.setVisible(true);
        CP_PHPLbl_OP.setVisible(true);
        CP_PHPLbl_OverallSales.setVisible(true);
        CPPoverallSales.setVisible(true);
        CPPoverallProfit.setVisible(true);
        CPPtotalSold.setVisible(true);
        CPPview.setVisible(false);
        
        
        // Request To DB
        ArrayList<ProductSummary> prod_sum_arr = provider.getProductRepo().getProductSummaries("Photocard");
        
        // Aggregate to Single Value
        int TotalQty = 0;
        double TotalSales = 0;
        double TotalProfit = 0;
        
        for( ProductSummary prod_sum : prod_sum_arr ) {
            TotalQty += prod_sum.getQty();
            TotalSales += prod_sum.getSales();
            TotalProfit += prod_sum.getProfit();
        }
        
        // Show Totals
        CPPoverallSales.setText(Double.toString(TotalSales));
        CPPoverallProfit.setText(Double.toString(TotalProfit));
        CPPtotalSold.setText(Integer.toString(TotalQty));
    }//GEN-LAST:event_jPanel17MouseEntered

    private void jPanel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseExited
        CP_OverallSalesLbl.setVisible(false);
        CP_OverallProfitLbl.setVisible(false);
        CP_TotalSoldLbl.setVisible(false);
        CP_PHPLbl_OP.setVisible(false);
        CP_PHPLbl_OverallSales.setVisible(false);
        CPPoverallSales.setVisible(false);
        CPPoverallProfit.setVisible(false);
        CPPtotalSold.setVisible(false);
        CPPview.setVisible(true);

    }//GEN-LAST:event_jPanel17MouseExited

    private void CPPviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPPviewMouseEntered
        CPPview.setBackground(Color.WHITE);
        CPPview.setForeground(new Color(38,38,38,255));
    }//GEN-LAST:event_CPPviewMouseEntered

    private void CPPviewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPPviewMouseExited
        CPPview.setBackground(new Color(38,38,38,255));
        CPPview.setForeground(Color.WHITE);
    }//GEN-LAST:event_CPPviewMouseExited

    private void CPPviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPPviewActionPerformed
        // TODO add your handling code here:
        jLabel43.setText("COSCARD/PHOTCARD PRINTING");
        
        // Request To DB
        ArrayList<ProductSummary> prod_sum_arr = provider.getProductRepo().getProductSummaries("Photocard");
        
        // Aggregate to Single Value
        int TotalQty = 0;
        double TotalSales = 0;
        double TotalProfit = 0;
        
        DefaultTableModel tableModel = (DefaultTableModel)table1.getModel();
        tableModel.setRowCount(0);
        
        for( ProductSummary prod_sum : prod_sum_arr ) {
            tableModel.addRow(
                    new Object[]{
                        prod_sum.getProductId(),
                        prod_sum.getName(),
                        prod_sum.getQty(),
                        prod_sum.getSales(),
                        prod_sum.getProfit()
                    }
            );
        }
    }//GEN-LAST:event_CPPviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPPoverallProfit;
    private javax.swing.JLabel CPPoverallSales;
    private javax.swing.JLabel CPPtotalSold;
    private javax.swing.JButton CPPview;
    private javax.swing.JLabel CP_OverallProfitLbl;
    private javax.swing.JLabel CP_OverallSalesLbl;
    private javax.swing.JLabel CP_PHPLbl_OP;
    private javax.swing.JLabel CP_PHPLbl_OverallSales;
    private javax.swing.JLabel CP_TotalSoldLbl;
    private javax.swing.JLabel PPPoverallProfit;
    private javax.swing.JLabel PPPoverallSales;
    private javax.swing.JLabel PPPtotalSold;
    private javax.swing.JButton PPPview;
    private javax.swing.JLabel PP_OverallProfitLbl;
    private javax.swing.JLabel PP_OverallSalesLbl;
    private javax.swing.JLabel PP_PHPLbl_OP;
    private javax.swing.JLabel PP_PHPLbl_OS;
    private javax.swing.JLabel PP_TotalSoldLbl;
    private javax.swing.JButton addRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel logBackground;
    private javax.swing.JPanel logoSide;
    private javax.swing.JPanel logoSide1;
    private javax.swing.JPanel logoSide3;
    private javax.swing.JPanel logoSide5;
    private javax.swing.JPanel logoSide6;
    private javax.swing.JButton signOut;
    private javax.swing.JTable table1;
    private javax.swing.JButton viewRecord;
    // End of variables declaration//GEN-END:variables
}
